Makefile: Make grub_fstest.pp depend on config-util.h
If you build with "make -j25", sometimes you see:

  /build/output_generic_x86_64/host/bin/x86_64-buildroot-linux-gnu-gcc -E -DHAVE_CONFIG_H -I. -I..  -Wall -W -DGRUB_UTIL=1 -D_FILE_OFFSET_BITS=64 -I./include -DGRUB_FILE=\"util/grub-fstest.c\" -I. -I.. -I. -I.. -I../include -I./include -I../grub-core/lib/libgcrypt-grub/src/ -I./grub-core/lib/gnulib -I../grub-core/lib/gnulib  -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Os -fno-stack-protector -D_FILE_OFFSET_BITS=64 \
    -D'GRUB_MOD_INIT(x)=@MARKER@x@' ../util/grub-fstest.c ../grub-core/kern/emu/hostfs.c ../grub-core/disk/host.c ../grub-core/osdep/init.c > grub_fstest.pp || (rm -f grub_fstest.pp; exit 1)
  config.status: creating config-util.h
  ../grub-core/kern/emu/hostfs.c:20:10: fatal error: config-util.h: No such file or directory
     20 | #include <config-util.h>
        |          ^~~~~~~~~~~~~~~
  compilation terminated.

Signed-off-by: Stefan Agner <stefan@agner.ch>
Reviewed-by: Daniel Kiper <daniel.kiper@oracle.com>