Fix -Wsign-compare warning for GCC 13
Since GCC 13, when an enum valud is our to int-type range, then all
enum values are promoted to the type. Thus, one gets the following
warning for HTTP_PORT value:

grub-core/net/http.c:414:48: error: operand of '?:' changes signedness
from 'int' to 'enum <anonymous>' due to unsignedness of other operand [-Werror=sign-compare]