blscfg: fix compilation on !EFI and !EMU
Neither GRUB_MACHINE_EFI nor GRUB_MACHINE_EMU are defined when compiling
for (eg) i386-pc. In this case, #elif GRUB_MACHINE_EMU is an error:

  commands/blscfg.c: In function ‘grub_cmd_blscfg’:
  commands/blscfg.c:835:7: error: "GRUB_MACHINE_EMU" is not defined [-Werror=undef]
   #elif GRUB_MACHINE_EMU
         ^~~~~~~~~~~~~~~~

Signed-off-by: Will Thompson <wjt@endlessm.com>