Fix prefix and root on ppc64le CDs
CHRP requires grub at /boot/grub.  On CDs, this means any other prefix
will be invalid.  In particular, a distro grub might prefer /grub2 - but
prefix is hardcoded into the signed core.elf, and will always be wrong
here.

Also work around a conflict between OF naming and that used by
part_msdos: on CDs, we always want the raw device.  This fixes an issue
where grub would successfully load the menu from an image, but then
produce the error:

    error: ../../grub-core/net/net.c:1552:disk `ieee1275/cdrom,0' not found.

and fail to boot further.

Signed-off-by: Robbie Harwood <rharwood@redhat.com>
(cherry picked from commit 68e5981a5e808a32350aca4a2414717fa4605ca0)
(cherry picked from commit 19c45257cc29845adedc3931eed577e97534f8f1)