remove unused varible
Otherwise compiler complains with:

../../grub-core/commands/efi/connectefi.c:143:20: error: unused variable ‘j’ [-Werror=unused-variable]
  143 |           unsigned j;
      |                    ^

Signed-off-by: Leo Sandoval <lsandova@redhat.com>