osdep/hurd/getroot: Remove unused variables in grub_util_find_hurd_root_device()
Found during a test build on Debian/hurd-i386 with --disable-werror enabled:

  In file included from grub-core/osdep/getroot.c:12:
  grub-core/osdep/hurd/getroot.c: In function ‘grub_util_find_hurd_root_device’:
  grub-core/osdep/hurd/getroot.c:126:13: error: unused variable ‘next’ [-Werror=unused-variable]
    126 |       char *next;
        |             ^~~~
  grub-core/osdep/hurd/getroot.c:125:14: error: unused variable ‘size’ [-Werror=unused-variable]
    125 |       size_t size;
        |              ^~~~

Fixes: e981b0a24 (osdep/hurd/getroot: Use "part:" qualifier)

Signed-off-by: John Paul Adrian Glaubitz <glaubitz@physik.fu-berlin.de>
Reviewed-by: Samuel Thibault <samuel.thibault@ens-lyon.org>
Reviewed-by: Daniel Kiper <daniel.kiper@oracle.com>