Revert "mm: Assert that we preserve header vs region alignment"
This reverts commit 1df8fe66c57087eb33bd6dc69f786ed124615aa7.

This is temporal while we find the reason for

In file included from ../../include/grub/mm_private.h:23,
                 from ../../include/grub/relocator_private.h:24,
                 from ../../grub-core/lib/efi/relocator.c:20:
../../include/grub/mm_private.h: In function ‘grub_mm_size_sanity_check’:
../../include/grub/misc.h:36:56: error: duplicate case value
   36 | #define COMPILE_TIME_ASSERT(cond) switch (0) { case 1: case !(cond): ; }
      |                                                        ^~~~
../../include/grub/mm_private.h:105:3: note: in expansion of macro ‘COMPILE_TIME_ASSERT’
  105 |   COMPILE_TIME_ASSERT ((sizeof (struct grub_mm_region) %
      |   ^~~~~~~~~~~~~~~~~~~
../../include/grub/misc.h:36:48: note: previously used here
   36 | #define COMPILE_TIME_ASSERT(cond) switch (0) { case 1: case !(cond): ; }
      |                                                ^~~~
../../include/grub/mm_private.h:105:3: note: in expansion of macro ‘COMPILE_TIME_ASSERT’
  105 |   COMPILE_TIME_ASSERT ((sizeof (struct grub_mm_region) %
      |   ^~~~~~~~~~~~~~~~~~~
../../include/grub/misc.h:36:56: error: duplicate case value
   36 | #define COMPILE_TIME_ASSERT(cond) switch (0) { case 1: case !(cond): ; }
      |                                                        ^~~~
../../include/grub/mm_private.h:112:3: note: in expansion of macro ‘COMPILE_TIME_ASSERT’
  112 |   COMPILE_TIME_ASSERT (sizeof (struct grub_mm_header) == GRUB_MM_ALIGN);
      |   ^~~~~~~~~~~~~~~~~~~
../../include/grub/misc.h:36:48: note: previously used here
   36 | #define COMPILE_TIME_ASSERT(cond) switch (0) { case 1: case !(cond): ; }
      |                                                ^~~~
../../include/grub/mm_private.h:112:3: note: in expansion of macro ‘COMPILE_TIME_ASSERT’
  112 |   COMPILE_TIME_ASSERT (sizeof (struct grub_mm_header) == GRUB_MM_ALIGN);
      |   ^~~~~~~~~~~~~~~~~~~