ieee1275/ofnet: Fix hw_addr variable initialization
The latest gcc does not like the initializer used for the
grub_net_link_level_address_t hw_addr variable:

../../grub-core/net/drivers/ieee1275/ofnet.c: In function ‘grub_ieee1275_parse_bootpath’:
../../grub-core/net/drivers/ieee1275/ofnet.c:158:3: warning: braces around scalar initializer
  158 |   grub_net_link_level_address_t hw_addr = {0, {{0, 0, 0, 0, 0, 0}}};
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../grub-core/net/drivers/ieee1275/ofnet.c:158:3: note: (near initialization for ‘hw_addr.len’)
../../grub-core/net/drivers/ieee1275/ofnet.c:158:3: error: braces around scalar initializer
../../grub-core/net/drivers/ieee1275/ofnet.c:158:3: note: (near initialization for ‘hw_addr.len’)
../../grub-core/net/drivers/ieee1275/ofnet.c:158:52: warning: excess elements in scalar initializer
  158 |   grub_net_link_level_address_t hw_addr = {0, {{0, 0, 0, 0, 0, 0}}};
...

Since we're zeroing it anyways switch to a simpler initializer
to fix this.

Signed-off-by: Hans de Goede <johannes.goede@oss.qualcomm.com>